### ISSUE TITLE
Code Review: firebase configs added to the wrong folder

### ISSUE THREAD

**Issue by albertogarza** [jkope/MovieAPI#65]
This firebase config: https://github.com/jkope/MovieAPI/blob/274644d206ba6c70bf3f66845fe453099530b8cc/src/app/APIKeys.ts#L2

is usually added to `src/environments/environment.ts`. I see a firebase config in there that is commented out. Why was it moved to `src/app/APIKeys.ts`?

**Comment by JerecTharen** [comment]
Followed instruction in the PDF file I was given in putting the firebase config stuff in the APIKeys.ts
That file has now been moved to the environments folder.
