### ISSUE TITLE
Code Review: Suggestion: Use a getter method for this

### ISSUE THREAD

**Issue by albertogarza** [jkope/MovieAPI#70]
Just as a suggestion, it's a lot cleaner to use a getter method  for these kinds of things:

https://github.com/jkope/MovieAPI/blob/704d4a830e67ac5e3baba944076a67a1271ef1ec/src/app/details/comments/comments.page.ts#L40

If you don't know what I'm talking about, let me know.

**Comment by jkope** [comment]
Created Getter for ID var in comments page
