### ISSUE TITLE
Code Review: Suggestion: Use resolver guards to grab initial data

### ISSUE THREAD

**Issue by albertogarza** [jkope/MovieAPI#71]
I noticed that you are grabbing a ton of data in an `ngOnInit()`: 

https://github.com/jkope/MovieAPI/blob/704d4a830e67ac5e3baba944076a67a1271ef1ec/src/app/details/comments/comments.page.ts#L41-L68

Although that's all and good, I prefer prefetching the data in a resolve guard (see https://angular.io/guide/router#resolve-pre-fetching-component-data as an example), especially when the code is as long as yours here. You may need multiple guards for what you're trying to fetch.

This is just a suggestion and don't feel you have to do it this way.

**Comment by jkope** [comment]
we looked into this and did use a resolver in another location to learn more about them. We decided not to go with one on the comments page because we wanted the user to have immediate feedback that their click worked and the details page is not very slow in loading anyway.
