### ISSUE TITLE
Code Review: Indentation is important

### ISSUE THREAD

**Issue by albertogarza** [jkope/MovieAPI#73]
Indentation is important. Here is an example of poor indentation:

https://github.com/jkope/MovieAPI/blob/704d4a830e67ac5e3baba944076a67a1271ef1ec/src/app/details/comments/comments.page.ts#L76-L85

More specifically, this line is not properly indented:

https://github.com/jkope/MovieAPI/blob/704d4a830e67ac5e3baba944076a67a1271ef1ec/src/app/details/comments/comments.page.ts#L78

You may want to consider using reformatting tools like WebStorm's Reformat Code option:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/7683492/52360683-d645b980-29f9-11e9-8bec-54c70d98d13d.png">

**Comment by jkope** [comment]
fixed all indenting/format
