### ISSUE TITLE
Code Review: Use specific types instead of any

### ISSUE THREAD

**Issue by albertogarza** [jkope/MovieAPI#81]
Like this line:
https://github.com/jkope/MovieAPI/blob/fcf0d7b9b8a129ecea21cbac8cf43eaf42c5d270/src/app/details/movie-details/movie-details.page.ts#L40

I was able to find about 8 matches in 7 files. That's pretty good! But could be better by not employing `any` in any of your project files.

This is just a suggestion. There are times where `any` is justified so don't go overboard with this.

**Comment by JerecTharen** [comment]
I have finished typing all properties, variables, and return types.
