### ISSUE TITLE
Code Review: TSLint messages

### ISSUE THREAD

**Issue by albertogarza** [jkope/MovieAPI#82]
This line:
https://github.com/jkope/MovieAPI/blob/b81811dbb430abbc667c53cdb7e67f9ffbfecaa9/src/app/details/detail-resolver.service.ts#L19

Gives me:
```
TSLint: Identifier 'id' is never reassigned; use 'const' instead of 'let'. (prefer-const)
```

And in that same file:
https://github.com/jkope/MovieAPI/blob/b81811dbb430abbc667c53cdb7e67f9ffbfecaa9/src/app/details/detail-resolver.service.ts#L22

Gives me:
```
TSLint: == should be === (triple-equals)
```

There's also another TSLint message:

```
TSLint: Missing semicolon (semicolon)
```
On lines 29 and 32 of the same file.

**Comment by albertogarza** [comment]
There's also another TSLint message:
```
TSLint: Missing semicolon (semicolon)
```

On lines 29 and 32 of the same file.

**Comment by jkope** [comment]
fixed
